package cn.beijing.ssfh.entity;

public class ClassRoomState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_state.classroom_state_id
     *
     * @mbggenerated
     */
    private Integer classroomStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_state.classroom_id
     *
     * @mbggenerated
     */
    private Integer classroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_state.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_state.classroom_state_id
     *
     * @return the value of classroom_state.classroom_state_id
     *
     * @mbggenerated
     */
    public Integer getClassroomStateId() {
        return classroomStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_state.classroom_state_id
     *
     * @param classroomStateId the value for classroom_state.classroom_state_id
     *
     * @mbggenerated
     */
    public void setClassroomStateId(Integer classroomStateId) {
        this.classroomStateId = classroomStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_state.classroom_id
     *
     * @return the value of classroom_state.classroom_id
     *
     * @mbggenerated
     */
    public Integer getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_state.classroom_id
     *
     * @param classroomId the value for classroom_state.classroom_id
     *
     * @mbggenerated
     */
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_state.state_id
     *
     * @return the value of classroom_state.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_state.state_id
     *
     * @param stateId the value for classroom_state.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
}