package cn.beijing.ssfh.entity;

public class GradeState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_state.grade_state_id
     *
     * @mbggenerated
     */
    private Integer gradeStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_state.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_state.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_state.grade_state_id
     *
     * @return the value of grade_state.grade_state_id
     *
     * @mbggenerated
     */
    public Integer getGradeStateId() {
        return gradeStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_state.grade_state_id
     *
     * @param gradeStateId the value for grade_state.grade_state_id
     *
     * @mbggenerated
     */
    public void setGradeStateId(Integer gradeStateId) {
        this.gradeStateId = gradeStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_state.grade_id
     *
     * @return the value of grade_state.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_state.grade_id
     *
     * @param gradeId the value for grade_state.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_state.state_id
     *
     * @return the value of grade_state.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_state.state_id
     *
     * @param stateId the value for grade_state.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
}