package cn.beijing.ssfh.entity;

public class State {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.class_room_state
     *
     * @mbggenerated
     */
    private Integer classRoomState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.teacher_state
     *
     * @mbggenerated
     */
    private Integer teacherState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.class_state
     *
     * @mbggenerated
     */
    private Integer classState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.state_id
     *
     * @return the value of state.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.state_id
     *
     * @param stateId the value for state.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.class_room_state
     *
     * @return the value of state.class_room_state
     *
     * @mbggenerated
     */
    public Integer getClassRoomState() {
        return classRoomState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.class_room_state
     *
     * @param classRoomState the value for state.class_room_state
     *
     * @mbggenerated
     */
    public void setClassRoomState(Integer classRoomState) {
        this.classRoomState = classRoomState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.teacher_state
     *
     * @return the value of state.teacher_state
     *
     * @mbggenerated
     */
    public Integer getTeacherState() {
        return teacherState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.teacher_state
     *
     * @param teacherState the value for state.teacher_state
     *
     * @mbggenerated
     */
    public void setTeacherState(Integer teacherState) {
        this.teacherState = teacherState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.class_state
     *
     * @return the value of state.class_state
     *
     * @mbggenerated
     */
    public Integer getClassState() {
        return classState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.class_state
     *
     * @param classState the value for state.class_state
     *
     * @mbggenerated
     */
    public void setClassState(Integer classState) {
        this.classState = classState;
    }
}