package cn.beijing.ssfh.entity;

public class TeacherState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_state.teacher_state_id
     *
     * @mbggenerated
     */
    private Integer teacherStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_state.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_state.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_state.teacher_state_id
     *
     * @return the value of teacher_state.teacher_state_id
     *
     * @mbggenerated
     */
    public Integer getTeacherStateId() {
        return teacherStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_state.teacher_state_id
     *
     * @param teacherStateId the value for teacher_state.teacher_state_id
     *
     * @mbggenerated
     */
    public void setTeacherStateId(Integer teacherStateId) {
        this.teacherStateId = teacherStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_state.state_id
     *
     * @return the value of teacher_state.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_state.state_id
     *
     * @param stateId the value for teacher_state.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_state.teacher_id
     *
     * @return the value of teacher_state.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_state.teacher_id
     *
     * @param teacherId the value for teacher_state.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}