package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.ClassRoomState;

public interface ClassRoomStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer classroomStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    int insert(ClassRoomState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    int insertSelective(ClassRoomState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    ClassRoomState selectByPrimaryKey(Integer classroomStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassRoomState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassRoomState record);
}